CREATE DATABASE Wakeerr;
USE Wakeerr;

CREATE TABLE User_ID (
    User_ID INT PRIMARY KEY,
    User_Name VARCHAR(255) NOT NULL,
    User_Email VARCHAR(255) NOT NULL,
    User_Password VARCHAR(255) NOT NULL
);